lung <- read.csv(file.choose())
View(lung)
attach(lung)
names(lung)
class(lung$Age)
lung$Age = as.numeric(lung$Age)
class(lung$Age)
plot(Age,LungCap,main="scatterplot")
LINEARMODEL = lm(LungCap~Age)
summary(LINEARMODEL)
attributes(LINEARMODEL)
plot(Age, LungCap, main="scatterplot")
abline(LINEARMODEL,col=2, lwd = 3)
checkLungs = data.frame(Age = 12)
res = predict(LINEARMODEL,checkLungs)
res
